### ISSUE TITLE
Can be removed the need for private methods start with underscore?

### ISSUE THREAD

**Issue by lfbn** [JBZoo/Utils#3]
Hi there,

Don't think that starting the function name of private methods with an underscore can be useful. Can this be removed from the ruleset?

Thanks!

**Comment by jncampbell** [comment]
+1

**Comment by SmetDenis** [comment]
Hi,

The public methods of any class is external API of library.
And it's really really really important to decide what information and actions have external access.

The leading underscore helps us to control that API in any place of code without documentations or IDE.  I think usually you are using publc methods of library and don't care about internal processes.

If some method become public we can rename it with IDE refactoring feature for a few seconds.

Developers in my company decided that we will use PSR Code Style with some minor fixes and check it via phpmd & phpcs with other tests. All ruleset save to [JBZoo/Misc](https://github.com/JBZoo/Misc) repository and you can easy add it to phpstorm.

Why do you think that undersoce is bad ? Do you have some bad practice with it ?

Thanks and best regards, Denis.

**Comment by lfbn** [comment]
Hi,

Yes, [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) disallow it:

> Method names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

Personally I don't think is useful, and according to [this thread](http://stackoverflow.com/questions/663350/whats-the-deal-with-a-leading-underscore-in-php-class-methods), this practice appeared because of poor implementation of OOP in PHP4, that didn't support visibility.

**Comment by SmetDenis** [comment]
Yes, I know.
I read really a lot of  threads and discussions about that before making the decision.

Very quick understanding what kind of method I'm using in class (public or not) is more important that PSR. Because external API of any class is very important stuff and developer should monitor that always. Nobody cares how class works - everybody use public methods of libs.

Underscore is easy method to do it without any docs or IDE. I can just look a code!

PSR standards are just some recommendations which based on [statistics](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#a3-survey-results). And it doesn't explain "why".

Anyway you can rename all methods in your fork and use it ;)

----
PS. PHP 4 died more then 10 years ago, so I never use it and don't know how it worked.

**Comment by lfbn** [comment]
Sorry, don't think this practice is useful. You should look at the method to see what he is doing. Then you see their visibility.

Maybe I'll fork it. :) Anyway, you can close this issue if you like.
